### ISSUE TITLE
problème fonction eScriptorium

### ISSUE THREAD

**Issue by ElsaVK** [HTR-United/cremma-wikipedia#11]
Bonjour,

Je suis entrain de travailler sur le batch4 et j'ai rencontré un petit soucis. Je ne sais pas si c'est le meilleur lieu pour en parler, mais je trouve que la fonction qui permet de "masquer" les lignes dans eScriptorium (la partie violette qui les détourne) s'est fortement dégradée depuis ma dernière utilisation de l'outil (en gros avant c'était automatique et ça marchait très bien mais maintenant c'est manuel en appuyant sur le pouce, et c'est beaucoup moins efficace). Est-ce normal ? On vous a déjà remonté le problème ?

Bien à vous,
Elsa

**Comment by ElsaVK** [comment]
Je dois repositionner chaque ligne à la main, ça m'embête de cramer mes crédits là dessus  :/

**Comment by alix-tz** [comment]
Salut Elsa, normalement le batch4 est déjà segmenté et le calcul des polygones devraient se faire en arrière plan sans que tu aies besoin de le déclencher toi-même. Il est possible de gérer ça à l'échelle de plusieurs documents en allant sur l'onglet "images", en sélectionnant les images concernées puis en cliquant sur "segment" et en prenant l'option "only mask" (ou quelque chose comme ça).

Ceci étant dit, j'ai remarqué qu'eScriptorium était très lent cet aprèm donc je pense qu'il y a aussi un problème passager d'embouteillage...

**Comment by alix-tz** [comment]
Je clos car je pense que c'est résolu.
