### ISSUE TITLE
organisation de la donnée

### ISSUE THREAD

**Issue by ElsaVK** [HTR-United/cremma-wikipedia#5]
Bonjour,

Je suis entrain de faire mes premiers push mais j'ai un doute quant à la forme finale des données. J'ai regroupé chaque .xml et .png dans un dossier individuel portant le nom du bach en question. Je ne sais plus pourquoi j'ai fait ça, je crois l'avoir vu dans une recommandation quelque part...Est-ce la bonne pratique ou bien je dois me contenter de mettre tous les fichiers en vrac dans le dossier data ?

Merci à vous,
Elsa

**Comment by PonteIneptique** [comment]
Pour l'organisation des données, je suis passé à côté de l'issue...

`data/batch-2/données du batch.xml` devrait suffire, je mets à jour la structure.

**Comment by alix-tz** [comment]
Oui, on sait déjà qu'en théorie 1 image = 1 écriture, donc ça me parait pas nécessaire de découper le batch

**Comment by ElsaVK** [comment]
Ok super merci, je ferme l'issue :)
